apiVersion: v1
kind: Service
metadata:
  name: my-service-1
  namespace: python-app
spec:
  type: NodePort
  selector:
    app: janani
    environment: production
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31313
